In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/world-happiness/2015.csv
/kaggle/input/world-happiness/2017.csv
/kaggle/input/world-happiness/2019.csv
/kaggle/input/world-happiness/2018.csv
/kaggle/input/world-happiness/2016.csv

In [2]:
df_2015 = pd.read_csv("../input/world-happiness/2015.csv")
df_2016 = pd.read_csv("../input/world-happiness/2016.csv")
df_2017 = pd.read_csv("../input/world-happiness/2017.csv")
df_2018 = pd.read_csv("../input/world-happiness/2018.csv")
df_2019 = pd.read_csv("../input/world-happiness/2019.csv")

In [3]:
df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [4]:
df_2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [5]:
df_2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [6]:
df_2018.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [7]:
df_2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

## Yıllara göre isimlendirmeler farklı olduğu için tek bir standarda indirgememiz gerekiyor.
## Since the naming is different according to the years, we need to reduce it to a single standard.

# for 2015

In [8]:
df_2015_ = df_2015.drop(['Region','Dystopia Residual','Standard Error'], axis=1)

In [9]:
cols15 = df_2015_.columns.tolist()
cols15

['Country',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity']

In [10]:
cols15 = ['Country',
'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
  'Generosity',
 'Trust (Government Corruption)']

In [11]:
temiz_df_2015 = df_2015_[cols15]

In [12]:
temiz_df_2015.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Generosity,Trust (Government Corruption)
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957

In [13]:
temiz_df_2015.columns = ["Country","Happiness Rank 2015","happiness Score 2015","Economy GDP 2015","Social 2015","Health 2015","Freedom 2015","Generosity 2015","Corruption 2015"]

In [14]:
temiz_df_2015.head()

,Country,Happiness Rank 2015,happiness Score 2015,Economy GDP 2015,Social 2015,Health 2015,Freedom 2015,Generosity 2015,Corruption 2015
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957

# for 2016

In [15]:
df_2016_ = df_2016.drop(["Lower Confidence Interval","Upper Confidence Interval",'Region','Dystopia Residual'], axis=1)

In [16]:
cols16 = df_2016_.columns.tolist()
cols16

['Country',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Trust (Government Corruption)',
 'Generosity']

In [17]:
cols16 = ['Country',
 'Happiness Rank',
 'Happiness Score',
 'Economy (GDP per Capita)',
 'Family',
 'Health (Life Expectancy)',
 'Freedom',
 'Generosity',
 'Trust (Government Corruption)']

In [18]:
temiz_df_2016 = df_2016_[cols16]

In [19]:
temiz_df_2016.columns = ["Country","Happiness Rank 2016","happiness Score 2016","Economy GDP 2016","Social 2016","Health 2016","Freedom 2016","Generosity 2016","Corruption 2016"]

In [20]:
temiz_df_2016.head()

,Country,Happiness Rank 2016,happiness Score 2016,Economy GDP 2016,Social 2016,Health 2016,Freedom 2016,Generosity 2016,Corruption 2016
0,Denmark,1,7.526,1.44178,1.16374,0.79504,0.57941,0.36171,0.44453
1,Switzerland,2,7.509,1.52733,1.14524,0.86303,0.58557,0.28083,0.41203
2,Iceland,3,7.501,1.42666,1.18326,0.86733,0.56624,0.47678,0.14975
3,Norway,4,7.498,1.57744,1.12690,0.79579,0.59609,0.37895,0.35776
4,Finland,5,7.413,1.40598,1.13464,0.81091,0.57104,0.25492,0.41004

# for 2017

In [21]:
temiz_df_2017 = df_2017.drop(["Whisker.high",'Whisker.low','Dystopia.Residual',], axis=1)

In [22]:
temiz_df_2017.columns = ["Country","Happiness Rank 2017","happiness Score 2017","Economy GDP 2017","Social 2017","Health 2017","Freedom 2017","Generosity 2017","Corruption 2017"]

In [23]:
temiz_df_2017.head()

,Country,Happiness Rank 2017,happiness Score 2017,Economy GDP 2017,Social 2017,Health 2017,Freedom 2017,Generosity 2017,Corruption 2017
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612

# for 2018

In [24]:
cols18 = df_2018.columns.tolist()
cols18

['Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [25]:
cols18 = ['Country or region',
 'Overall rank',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [26]:
temiz_df_2018 = df_2018[cols18]

In [27]:
temiz_df_2018.columns = ["Country","Happiness Rank 2018","happiness Score 2018","Economy GDP 2018","Social 2018","Health 2018","Freedom 2018","Generosity 2018","Corruption 2018"]

In [28]:
temiz_df_2018.head()

,Country,Happiness Rank 2018,happiness Score 2018,Economy GDP 2018,Social 2018,Health 2018,Freedom 2018,Generosity 2018,Corruption 2018
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.256,0.357

# for 2019

In [29]:
cols19 = df_2019.columns.tolist()
cols19

['Overall rank',
 'Country or region',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [30]:
cols19 = ['Country or region',
 'Overall rank',
 'Score',
 'GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption']

In [31]:
temiz_df_2019 = df_2019[cols19]

In [32]:
temiz_df_2019.columns = ["Country","Happiness Rank 2019","happiness Score 2019","Economy GDP 2019","Social 2019","Health 2019","Freedom 2019","Generosity 2019","Corruption 2019"]

In [33]:
temiz_df_2019.head()

,Country,Happiness Rank 2019,happiness Score 2019,Economy GDP 2019,Social 2019,Health 2019,Freedom 2019,Generosity 2019,Corruption 2019
0,Finland,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,5,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [34]:
df_15_16 =pd.merge(temiz_df_2015,temiz_df_2016, on='Country', how='inner')

In [35]:
df_17_18 =pd.merge(temiz_df_2017,temiz_df_2018, on='Country', how='inner')

In [36]:
df_15_16_17_18 =pd.merge(df_15_16,df_17_18, on='Country', how='inner')

In [37]:
df = pd.merge(df_15_16_17_18,temiz_df_2019, on='Country', how='inner')

In [38]:
df

,Country,Happiness Rank 2015,happiness Score 2015,Economy GDP 2015,Social 2015,Health 2015,Freedom 2015,Generosity 2015,Corruption 2015,Happiness Rank 2016,...,Generosity 2018,Corruption 2018,Happiness Rank 2019,happiness Score 2019,Economy GDP 2019,Social 2019,Health 2019,Freedom 2019,Generosity 2019,Corruption 2019
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2,...,0.256,0.357,6,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,3,...,0.353,0.138,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,1,...,0.284,0.408,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,4,...,0.286,0.340,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,6,...,0.321,0.291,9,7.278,1.365,1.505,1.039,0.584,0.285,0.308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Rwanda,154,3.465,0.22208,0.77370,0.42864,0.59201,0.22628,0.55191,152,...,0.200,0.444,152,3.334,0.359,0.711,0.614,0.555,0.217,0.411
137,Benin,155,3.340,0.28665,0.35386,0.31910,0.48450,0.18260,0.08010,153,...,0.163,0.067,102,4.883,0.393,0.437,0.397,0.349,0.175,0.082
138,Syria,156,3.006,0.66320,0.47489,0.72193,0.15684,0.47179,0.18906,156,...,0.376,0.144,149,3.462,0.619,0.378,0.440,0.013,0.331,0.141
139,Burundi,157,2.905,0.01530,0.41587,0.22396,0.11850,0.19727,0.10062,157,...,0.149,0.076,145,3.775,0.046,0.447,0.380,0.220,0.176,0.180
140,Togo,158,2.839,0.20868,0.13995,0.28443,0.36453,0.16681,0.10731,155,...,0.158,0.101,139,4.085,0.275,0.572,0.410,0.293,0.177,0.085

## Hangi ülkeler veya bölgeler genel mutlulukta ve mutluluğa katkıda bulunan altı faktörün her birinde en yüksek sırada yer alıyor?

In [39]:
_1st_2015 = df.loc[df['Happiness Rank 2015']== 1]["Country"][0]
_1st_2016 = df.loc[df['Happiness Rank 2016']== 1]["Country"][2]
_1st_2017 = df.loc[df['Happiness Rank 2017']== 1]["Country"][3]
_1st_2018 = df.loc[df['Happiness Rank 2018']== 1]["Country"][5]
_1st_2019 = df.loc[df['Happiness Rank 2019']== 1]["Country"][5]

In [40]:
print("2015 mutlulukta birinci ülke : {}".format(_1st_2015))
print("2016 mutlulukta birinci ülke : {}".format(_1st_2016))
print("2017 mutlulukta birinci ülke : {}".format(_1st_2017))
print("2018 mutlulukta birinci ülke : {}".format(_1st_2018))
print("2019 mutlulukta birinci ülke : {}".format(_1st_2019))

2015 mutlulukta birinci ülke : Switzerland
2016 mutlulukta birinci ülke : Denmark
2017 mutlulukta birinci ülke : Norway
2018 mutlulukta birinci ülke : Finland
2019 mutlulukta birinci ülke : Finland

## Herhangi bir ülke mutlulukta önemli bir artış veya azalma yaşadı mı?

In [41]:
df

,Country,Happiness Rank 2015,happiness Score 2015,Economy GDP 2015,Social 2015,Health 2015,Freedom 2015,Generosity 2015,Corruption 2015,Happiness Rank 2016,...,Generosity 2018,Corruption 2018,Happiness Rank 2019,happiness Score 2019,Economy GDP 2019,Social 2019,Health 2019,Freedom 2019,Generosity 2019,Corruption 2019
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2,...,0.256,0.357,6,7.480,1.452,1.526,1.052,0.572,0.263,0.343
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,3,...,0.353,0.138,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,1,...,0.284,0.408,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,4,...,0.286,0.340,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,6,...,0.321,0.291,9,7.278,1.365,1.505,1.039,0.584,0.285,0.308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Rwanda,154,3.465,0.22208,0.77370,0.42864,0.59201,0.22628,0.55191,152,...,0.200,0.444,152,3.334,0.359,0.711,0.614,0.555,0.217,0.411
137,Benin,155,3.340,0.28665,0.35386,0.31910,0.48450,0.18260,0.08010,153,...,0.163,0.067,102,4.883,0.393,0.437,0.397,0.349,0.175,0.082
138,Syria,156,3.006,0.66320,0.47489,0.72193,0.15684,0.47179,0.18906,156,...,0.376,0.144,149,3.462,0.619,0.378,0.440,0.013,0.331,0.141
139,Burundi,157,2.905,0.01530,0.41587,0.22396,0.11850,0.19727,0.10062,157,...,0.149,0.076,145,3.775,0.046,0.447,0.380,0.220,0.176,0.180
140,Togo,158,2.839,0.20868,0.13995,0.28443,0.36453,0.16681,0.10731,155,...,0.158,0.101,139,4.085,0.275,0.572,0.410,0.293,0.177,0.085

In [42]:
cols = ["Happiness Rank 2015" ,"Happiness Rank 2016" ,"Happiness Rank 2017" ,"Happiness Rank 2018" ,"Happiness Rank 2019"]

In [43]:
df_rank = df[cols]

In [44]:
df_rank

,Happiness Rank 2015,Happiness Rank 2016,Happiness Rank 2017,Happiness Rank 2018,Happiness Rank 2019
0,1,2,4,5,6
1,2,3,3,4,4
2,3,1,2,3,2
3,4,4,1,2,3
4,5,6,7,7,9
...,...,...,...,...,...
136,154,152,151,151,152
137,155,153,143,136,102
138,156,156,152,150,149
139,157,157,154,156,145
140,158,155,150,139,139